# Based on theme: https://github.com/niklasbuschmann/contrast

title: EvDev
author: "Evgeny Yakimov"
email: evgeny@evdev.me
lang: "en"
description: >- # this means to ignore newlines until "baseurl:"
  The tech escapades of a software engineer turned SRE in the world of
  containerization, cloud, monitoring, tracing and many more concepts
  still to be explored!

# Theme settings
show_footer: true            # show the "previous" and "next" links at the end of each post
dark_theme: true             # use the dark mode as default
dark_header: false           # keep the header dark
dark_footer: false           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
paginate: 8                  # use "layout: paginate" in the index.html to enable pagination

navigation:                  # site navigation in the header
  - index.html
  - about.md
  - contact.html
  - search.html

icons:                      # icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:evgeny@evdev.me"
  twitter: "https://twitter.com/TheEvDev"
  github: "https://github.com/eyjohn"
  linkedin: "https://www.linkedin.com/in/evgeny-yakimov-7370848/"
  rss: "/feed.xml"

comments:                    # embed disqus or isso comments
  disqus: "evdev"
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
 - jekyll-remote-theme

remote_theme: niklasbuschmann/contrast@v1.0
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - docker_jekyll
  - firebase.json
