#!/bin/bash
docker volume create "jekyll_cache_$(basename $(pwd))"
docker run --rm \
  --volume="$PWD:/srv/jekyll" \
  --volume="jekyll_cache_$(basename $(pwd)):/usr/local/bundle" \
  --expose 4000 \
  --net host \
  -it jekyll/jekyll "$@"
